---

cluster_name: "test"

rke_config_dir: "/opt/rke/"

# This is the host that will run 'rke up'
# By default, use the first host in the play
rke_controller_hostname: "{{ ansible_play_hosts[0] }}"

rke_ssh_user: rke_user


# Private registry 
private_registry_url: https://test:1111/
private_registry_user: tset
private_registry_password: test_password