---

cluster_name: "test"

rke_config_dir: "/opt/rke/"
rke_force_configure: false

# This is the host that will run 'rke up'
# By default, use the first host in the play
rke_controller_hostname: "{{ ansible_play_hosts[0] }}"

# Networking configuration
cluster_interface: "{{ ansible_default_ipv4.interface }}"
cluster_cidr: "{{ [ansible_facts[cluster_interface].ipv4.network, ansible_facts[cluster_interface].ipv4.netmask] | join('/') | ipaddr('net') }}"

rke_ssh_user: rke_user

openstack_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"

rke_network_config:
  plugin: canal
  options:
    canal_iface: "{{ cluster_interface }}"

rke_ingress_config:
  provider: nginx

manifests_dir: "{{ ansible_env.HOME | default(ansible_env.PWD) | default('/root') }}/manifests"