- name: Determine if user 10010 exists
  command: id -nu 10010
  register: user_10010
  ignore_errors: yes

- name: Create rke user
  user:
    name: "{{ rke_ssh_user }}"
    password: "{{ rke_ssh_user_password }}"
    uid: 10010
    group: docker
  when: not user_10010.stdout | d("")