- name: Determine if user 10010 exists
  command: id -nu 10010
  register: user_10010
  ignore_errors: yes

- name: Create rke user
  user:
    name: "{{ rke_ssh_user }}"
    uid: 10010
    group: nobody
  when: not user_10010.stdout | d("")

- name: Creates directory
  file:
    path: "{{ rke_config_dir }}"
    state: directory

- name: Create/update RKE config file
  template:
    src: rke_cluster.yml.j2
    dest: "{{ rke_config_dir }}/rke_cluster.yml"
    mode: u=rw,g=r,o=
  register: rke_cluster_config

- name: Run RKE
  shell: rke up --config ./rancher-cluster.yml
  remote_user: "{{ rke_ssh_user }}"
  args:
    chdir: "{{ rke_config_dir }}"