---

###
# RKE
###

# Version
rke_version: "v1.1.3"

# Binary URL
rke_binary_url: "https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64"

# Local binary path
rke_install_dir: "/usr/local/bin"
