- name: Determine if kubectl is installed
  command: which kubectl
  register: kubectl_installed
  ignore_errors: true
  changed_when: false

- name: kubectl | Install
  block:
    - name: Install kubectl from YUM repo
      yum:
        name: kubectl
        state: present
  rescue:
    - name: Install kubectl from local
      shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  when: kubectl_installed['failed']
